
log syslog all;

router id 192.168.xxx.xxx;

include "asn_cn.conf";

protocol device {
        scan time 10;
}

protocol static {
        ipv4 {};
}

protocol static {
        ipv6 {};
}

# BGP peers
protocol bgp bwgv4 {
        #debug all;
        description "BGP link bwg";
        local as 65533;
        neighbor 10.x.x.x as 65535;
        #keepalive time 5;
        #connect retry time 10;
        #direct;
        multihop 2;
        source address 10.x.x.x;
        password "xxxxxx";
        ipv4 {
                import all;
                export none;
                };
        graceful restart on;
        #bfd on;
} 

# BGP peers
protocol bgp bwgv6 {
        #debug all;
        description "BGP link bwg";
        local as 65533;
        neighbor fdxx:42xx:xxxx as 65535;
        #keepalive time 5;
        #connect retry time 10;
        #direct;
        multihop 2;
        source address fdxx:42xx:xxxx;
        password "xxxxxx";
        ipv6 {
                import all;
                export none;
                };
        graceful restart on;
        #bfd on;
} 

# BGP peers
protocol bgp rosv4 {
        description "BGP link rosv4";
        interface "eth0";
        local as 65523;
        neighbor 192.168.xxx.xxx as 65525;
        keepalive time 5;
        connect retry time 10;   
        med metric;
        direct;   
        source address 192.168.xxx.xxx;
        ipv4 {  
                #next hop self;
                #gateway direct;
                import none;
                export filter {
                        #if bgp_path ~ [4134, 4809, 36678, 4837, 9929, 9808, 9394, 4538, 23910] then accept; else reject;
                        if bgp_path ~ china_asn then accept; else reject;
                };
  };
        graceful restart on;
        #bfd on;
}


protocol bgp rosv6 {
        #debug all;
        description "BGP link rosv6";
        interface "eth0";
        local as 65523;
        neighbor fd22::xxx as 65525;
        keepalive time 5;
        connect retry time 10;   
        med metric;
        direct;   
        source address fd22::xxx;
        ipv6 {
                import none;
                export filter {
                        #if bgp_path ~ [4134, 4809, 36678, 4837, 9929, 9808, 9394, 4538, 23910] then accept; else reject;
                        if bgp_path ~ china_asn then accept; else reject;
                };
  };
        graceful restart on;
        #bfd on;
}


# BGP bfd
protocol bfd Nodes {
    interface "ztdpbodawa" {
        min rx interval 100 ms;
        min tx interval 100 ms;
        idle tx interval 300 ms;
        multiplier 10;
        password "xxxxxx";
      };
    interface "eth0@ifxx" {
        min rx interval 100 ms;
        min tx interval 100 ms;
        idle tx interval 300 ms;
        multiplier 10;
        authentication none;
      };  
      neighbor 10.0.8.1 dev "ztdpbodawa";
      neighbor fd0f:42d2:14xx:33xx:40xx:93xx:42xx:14xx dev "ztdpbodawa";
      neighbor 192.168.xxx.x dev "eth0@ifxx";
      neighbor fdxx::x dev "eth0@ifxx";
}
